### ISSUE TITLE
Zeitwerk::NameError

### ISSUE THREAD

**Issue by karthickattabomman** [solidusio/solidus_auth_devise#193]
(expected file /home/maddy/Sites/DeviceMailer/app/controllers/registrations_controller.rb to define constant RegistrationsController, but didn't):

**Comment by jarednorman** [comment]
Unfortunately, you've provided almost no context around this error, but if I had to guess I'd assume you've just set up a new Solidus app on Rails 6 (using the Zeitwerk autoloader) and wanted to make modifications to the registrations controlle and that the file referenced contains those modifications. If that's correct, then you should consider [using a decorator](https://guides.solidus.io/developers/customizations/decorators.html) to make the modifications and may also want to review [the docs on project file structure and Zeitwerk](https://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#project-structure) as the error you've encountered is directly related to that.

It's not clear from the details you provided (which don't reference any files from this extension) that you've encountered a bug in the extension itself. If this is more of a support request, please instead us the #support channel on [the Solidus Slack](https://slack.solidus.io/). Whether you follow up here or in Slack, more context would be very helpful:

- What version of Ruby, Rails, Solidus, and solidus_auth_devise are you using?
- What were you trying to do when you experienced this error?
- What have you done to try to resolve this error?
- What's in the file `app/controllers/registrations_controller.rb`? That's a file in _your_ app, not in this extension, so it's not clear what's going on.

I'm closing this issue due to lack of details and because there's no evidence this is a bug in this extension. Please feel free to follow up with more information (so we can reopen the issue if it really is a bug) or take the issue to our #support channel. 🙂
